language: python
python:
  - "2.6"
  - "2.7"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"
  fast_finish: true

# Route build to container-based infrastructure
sudo: false

# Cache the dependencies installed by pip
cache: pip
# Avoid pip log from affecting cache
before_cache: rm -fv ~/.cache/pip/log/debug.log

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

# Commands that prepare things for the test
before_script:
  - export PYTHONPATH=$PYTHONPATH:`pwd -P`
  - cd test

script: coverage run --branch --source=apel,bin -m unittest2 discover --buffer

after_success: coveralls
